
<div align="center">
<h2>Uživatelské menu</h2>
<hr>
<p>
        jste přihlášen jako <b><?= $status ?></b> a toto jsou vaše funkce:
</p>
<?php if ($status == "autor") : ?>
        <h2><a href="myArticles" class="btn btn-default" role="button">Moje články</a></h2><br />
        <h2><a href="editor" class="btn btn-default" role="button">Přidat nový článek</a></h2><br />
<?php elseif ($status == "recenzent") : ?>
        <h2><a href="myReviews" class="btn btn-default" role="button">Moje články k recenzi</a></h2><br />
<?php elseif ($status == "administrator") : ?>
        <h2><a href="users" class="btn btn-default" role="button">Seznam uživatelů</a></h2><br />
        <h2><a href="reviews" class="btn btn-default" role="button">Spravovat recenzenty</a></h2><br />
<?php endif; ?>

</div>

