<header>

    <h3><?= $title ?></h3>
</header>
<hr>
<section>
    <strong>Abstract:</strong> <?= $_abstract ?>
    <?php
        $dir = new DirectoryIterator('articles');
        foreach ($dir as $fileName) {
            if (!$fileName->isDot()) {
                if (substr($fileName, 0, strlen($url)) == $url) {
                    echo"<a href='editor/display/$fileName.add' class='btn btn-default' role='button'>Stáhnout celý článek</a>";
                }
            }
        }
    ?>
    <br/><br/>
</section>