<h2>Seznam článků</h2>
(klikněte na název pro detail)
<?php $i = 1; ?>
<div class="table-responsive">
<table id="userTable" class="table table-striped table-hover">
<?php foreach ($articles as $article) : ?>
        <tr align="center">
        <th scope="row"><?php echo $i++;?> </th>
                
        <td><h2><a href="article/<?= $article['url'] ?>"><?= $article['title'] ?></a></h2></td>
        <td>  <?= $article['description'] ?></td>
        <td>     <?php if ($status == 'administrator') : ?></td>
                                <br /></td>
                                <td>    <a href="editor/<?= $article['article_id'] ?>" class="btn btn-default" role="button">Editovat</a> <br /></td>
                                <td>    <a href="article/<?= $article['url'] ?>/remove" class="btn btn-default" role="button">Odstranit</a></td>
                                <?php endif ?>
                
        </tr>
<?php endforeach ?>

<?php if(empty($articles)) : ?>
<p><br />
        Seznam článků je bohužel prázdný.
</p>
<?php endif ?>
</table>
</div>