<h1>Editor článků</h1>
<div class="form-group">
<form method="post" encytype="multipart/form-data">
        Titulek<br />
        <input type="text" name="title" value="<?= $article['title'] ?>" /><br />
        Pdf<br />
        <input type="hidden" name="MAX_FILE_SIZE" value="2000000">
        <input name="pdf" value="<?= $article['pdf']?>" class="btn btn-default" role="button" type="file"><br />
        Abstrakt<br />
        <textarea name="abstract"><?= $article['abstract'] ?></textarea><br />
                
        Popisek<br />
        <input type="text" name="description" value="<?= $article['description'] ?>" /><br />

        URL<br />
        <input type="text" name="url" value="<?= $article['url'] ?>" /><br />

        Klíčová slova<br />
        <input type="text" name="keywords" value="<?= $article['keywords'] ?>" /><br />

        <input type="submit" class="btn btn-default" role="button" value="Uložit článek" />
</form>
</div>

<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script type="text/javascript">
        tinymce.init({
                        selector: "textarea[name=abstract]",
                        plugins: [
                                        "advlist autolink lists link image charmap print preview anchor",
                                        "searchreplace visualblocks code fullscreen",
                                        "insertdatetime media table contextmenu paste"
                        ],
                        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
                        entities: "160,nbsp",
                        entity_encoding: "named",
                        entity_encoding: "raw"
        });
</script>