<h1>Editor článků</h1>
<form enctype="multipart/form-data" method="POST">
        <label for="titleB">Titulek článku</label>
        <input id="titleB" class="form-text" name="title" value="<?= $article['title'] ?>" /><br />

        <input type="hidden" name="MAX_FILE_SIZE" value="2000000">
        <label for="file">PDF článku</label><br />
        <input type="file" name="file" class="form-control-file" id="file" accept="application/pdf"><br /><br />

        <label for="abs">Abstrakt článku</label>
        <textarea id="abs" class="form-control" rows="5" name="abstract"><?= $article['abstract'] ?></textarea><br />
                
        <label for="descr">Stručný popis článku</label>
        <input id="descr" class="form-text" name="description" value="<?= $article['description'] ?>" /><br />

        <label for="url">Konec URL (malá písmena bez diakritiky)</label>
        <input id="url" class="form-text" name="url" value="<?= $article['url'] ?>" /><br />

        <label for="keywords">Klíčová slova</label>
        <input id="keywords" class="form-text" name="keywords" value="<?= $article['keywords'] ?>" /><br />
        <br />
        <input type="submit" value="Uložit článek" class="btn btn-default" role="button"/><br /><br />
        <!-- <input type="submit" class="btn btn-default" role="button" value="Uložit článek" /> -->
</form>

<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script type="text/javascript">
        tinymce.init({
                        selector: "textarea[name=abstract]",
                        plugins: [
                                        "advlist autolink lists link image charmap print preview anchor",
                                        "searchreplace visualblocks code fullscreen",
                                        "insertdatetime media table contextmenu paste"
                        ],
                        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
                        entities: "160,nbsp",
                        entity_encoding: "named",
                        entity_encoding: "raw"
        });
</script>



