<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keywords ?>" />
        <link rel="stylesheet" href="style.css" type="text/css"/>
        </head>

        <body>
            <header>
                <h1>ITnetworkMVC - ukázkový web</h1>
            </header>
            <?php foreach ($messages as $message) : ?>
                <p class="message"><?= $message ?></p>
            <?php endforeach ?>
            <nav>
                <ul>
                    <li><a href="article/uvod">Úvod</a></li>
                    <li><a href="article">Články</a></li>
                    <li><a href="contact">Kontakt</a></li>
                </ul>
            </nav>
            <br clear="both" />

            <article>
                <?php $this->controller->printView(); ?>
            </article>

        <footer>
            <p><a href="administrace">Administrace</a></p>
        </footer>
    </body>

</html>