<!DOCTYPE html>
<html lang="cs-cz">
        <head>
                <base href="/localhost" />
                <meta charset="UTF-8" />
                <title><?php echo $title ?></title>
                <meta name="description" content="<?php echo $description ?>" />
                <meta name="keyWords" content="<?php echo $keyWords ?>" />
                <link rel="stylesheet" href="style.css" type="text/css"/>
        </head>

        <body>
                <header>
                        <h1>Česká jazyková konference 2020</h1>
                </header>

                <nav>
                        <ul>
                                <li><a href="clanek/uvod">Úvod</a></li>
                                <li><a href="clanek">Články</a></li>
                                <li><a href="kontakt">Kontakt</a></li>
                        </ul>
                </nav>
                <br clear="both" />

                <article>

                </article>

                <footer>
                        <p>Patička.</p>
                </footer>
        </body>
</html>