<div  align="center">
<h2>Přihlášení do administrace</h2>
<hr>
<form method="post">
        <label for="nam">Uživatelské jméno</label>
        <input id="nam" type="text" class="form-text" name="username" /><br />
        <label for="pass">Heslo</label>
        <input id="pass" type="password" class="form-text" name="password" /><br />
<br />
        <input class="btn btn-default" role="button" type="submit" value="Přihlásit" />
</form>
<br />
<p align="center">
        Pokud ještě nemáte účet, 
        <a href="registration">
                zaregistrujte se zde
        </a>.
</p>
</div>