<h2>Přihlášení do administrace</h2>
<hr>
<form method="post">
        Jméno<br />
        <input type="text" name="username" /><br />
        Heslo<br />
        <input type="password" name="password" /><br />
<br />
        <input class="btn btn-default" role="button" type="submit" value="Přihlásit" />
</form>
<br />
<p>Pokud ještě nemáte účet, <a href="registration">zaregistrujte se zde</a>.</p>