<h2>Seznam mých článků</h2>
<?php $i = 1; ?>

<h2><a href="editor" class="btn btn-default" role="button">Přidat nový článek</a></h2><br />



<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr align="center">
      <th scope="col">Řádek</th>
      <th scope="col">ID článku</th>
      <th scope="col">Titulek</th>
      <th scope="col">Abstrakt</th>
      <th scope="col">Pdf</th>
      <th scope="col">Stav</th>
      <th scope="col">Skóre</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($articles as $article) : ?>
          <tr align="center">
                      <th scope="row"><?php echo $i++;?> </th>
                      <td><?= $article['article_id'] ?></td>
                        <?php
                          echo"<td><a href='myArticles/alter/".$article['article_id']."'>upravit příspěvek</a></td>";
                        ?>
                  </tr>
          <?php endforeach ?>
    </tbody>
  </table>
</div>