<h2>Moje články</h2>
<?php $i = 1; ?>

<h2><a href="editor" class="btn btn-default" role="button">Přidat nový článek</a></h2><br />



<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr align="center">
      <th scope="col">Řádek</th>
      <th scope="col">ID článku</th>
      <th scope="col">Titulek</th>
      <th scope="col">Popis</th>
      <th scope="col">Stav</th>
      <th scope="col">Skóre</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($articles as $article) : ?>
          <tr align="center">
                      <th scope="row"><?php echo $i++;?> </th>
                      <td><?= $article['article_id'] ?></td>
                      <td><?= $article['title'] ?></td>
                      <td><?= $article['description'] ?></td>
                      <td><?= $article['status'] ?></td>
                      <td><?= $article['score'] ?></td>
                        <?php
                          echo"<td><a href='editor/". $article['article_id'] ."' class='btn btn-default' role='button'>upravit příspěvek</a></td>";
                          echo"<td><a href='article/" . $article['url'] . "/remove' class='btn btn-default' role='button'>Odstranit</a></td>";
                        ?>
                  </tr>
          <?php endforeach ?>
    </tbody>
  </table>
</div>

<?php if(empty($articles)) : ?>
<p>
        Ještě jsem nepřidal žádný článek.
</p>
<?php endif ?>