<h2>Seznam mých článků k recenzi</h2>
<?php $i = 1; ?>
<?php if(empty($myArticles)) : ?>
<p>
       Momentálně nemáte přidělený žádný článek.
</p>
<?php else: ?>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr align="center">
      <th scope="col">Řádek</th>
      <th scope="col">ID článku</th>
      <th scope="col">Článek</th>
      <th scope="col">Popis</th>
      <th scope="col">Stav</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($myArticles as $article) : ?>
          <tr align="center">
                      <th scope="row"><?php echo $i++;?> </th>
                      <td><?= $article['article_id'] ?></td>
                      <td> <a href="article/<?= $article['url'] ?>"><?= $article['title'] ?></a></td>
                      <td><?= $article['description'] ?></td>
                      <td><?= $article['status'] ?></td>
                        <?php
                          if ($article['status'] == 'k recenzi') {
                            echo"<td><a href='myReviews/prepare/". $article['article_id'] ."' class='btn btn-default' role='button'>Připravit recenzi</a></td>";
                          }
                          else {
                            echo"<td><a href='myReviews/edit/" . $article['article_id'] . "' class='btn btn-default' role='button'>Editovat recenzi</a></td>";
                            echo"<td><a href='myReviews/remove/" . $article['article_id'] . "' class='btn btn-default' role='button'>Smazat recenzi</a></td>";
                          }
                        ?>
                  </tr>
          <?php endforeach ?>
    </tbody>
  </table>
</div>

<?php endif; ?>