<h2>Seznam článků</h2>
<?php $i = 1; ?>


<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr align="center">
      <th scope="col">Řádek</th>
      <th scope="col">ID článku</th>
      <th scope="col">Titulek</th>
      <th scope="col">Popis</th>
      <th scope="col">Stav</th>
      <th scope="col">Skóre</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($reviews as $review) : ?>
          <tr align="center">
                      <th scope="row"><?php echo $i++;?> </th>
                      <td><?= $review['review_id'] ?></td>
                      <td><?= $review['title'] ?></td>
                      <td><?= $review['description'] ?></td>
                      <td><?= $review['status'] ?></td>
                      <td><?= $review['score'] ?></td>
                        <?php
                          echo"<td><a href='editor/". $review['review_id'] ."' class='btn btn-default' role='button'>upravit příspěvek</a></td>";
                          echo"<td><a href='review/" . $review['url'] . "/remove' class='btn btn-default' role='button'>Odstranit</a></td>";
                        ?>
                  </tr>
          <?php endforeach ?>
    </tbody>
  </table>
</div>

<?php if(empty($reviews)) : ?>
<p>
        Seznam recenzí je bohužel prázdný.
</p>
<?php endif ?>