<h1>Registrace</h1>

<form method="post">
        Jméno<br />
        <input type="text" name="name" /><br />
        Heslo<br />
        <input type="pass" name="pass" /><br />
        Heslo znovu<br />
        <input type="pass" name="passAgain" /><br />
        Zadejte aktuální rok (antispam)<br />
        <input type="text" name="year" /><br />
        <input type="submit" value="Registrovat" />
</form>