<h2>Registrace</h2>
<hr>
<form method="post">
        <label for="username"><b>Jméno</b></label><br />
        <input type="text" name="username" /><br />
        <label for="password"><b>Heslo</b></label><br />
        <input type="password" name="password" /><br />
        <label for="password_again"><b>Heslo znovu</b></label><br />
        <input type="password" name="password_again" /><br />
        Zadejte aktuální rok (antispam)<br />
        <input type="text" name="year" /><br /><br />
        <input type="submit" class="btn btn-default" role="button" value="Registrovat" />
</form>