<h2>Registrace</h2>
<hr>
<form method="post" align="center">
        <label for="username"><strong>Jméno</strong></label><br />
        <input type="text" name="username" /><br />
        <label for="password"><strong>Heslo</strong></label><br />
        <input type="password" name="password" /><br />
        <label for="password_again"><strong>Heslo znovu</strong></label><br />
        <input type="password" name="password_again" /><br /><br />
        <input type="submit" class="btn btn-default" role="button" value="Registrovat" /><br /><br />
</form>