<h2>Seznam recenzí</h2>
<hr>
<table class="table table-striped table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">ID v databázi</th>
      <th scope="col">Uživatelské jméno</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($reviews as $review) : ?>
                <tr>
                    <td><?= $review['review_id'] ?></td>
                    <td><div class="form-check">
                        <input type="checkbox" class="form-check-input" id="materialUnchecked">
                        <label class="form-check-label" for="materialUnchecked"></label>
                    </div></td>
                </tr>
        <?php endforeach ?>
  </tbody>
</table>
<div class="text-center">
<input type="submit" class="btn btn-success" role="button" value="Povýšit označené" /></div>

