<h2>Seznam recenzí</h2>
<?php $i = 1; ?>
<div class="table-responsive">
  <table id="reviewTable" class="table table-striped table-hover">
    <thead>
      <tr align="center">
      <th scope="col">ID uživatele</th>
      <th scope="col">Uživatelské jméno</th>
        <!-- <th scope="col">Smazat</th> -->
      </tr>
    </thead>
    <tbody>
      <?php foreach ($reviews as $review) : ?>
          <tr align="center">
                      <th scope="row"><?php echo $i++;?> </th>
                      <td><?= $review['review_id'] ?></td>
                        <?php
                          echo"<td><a href='administration/delete/".$user['user_id']."'>odstranit uživatele</a></td>";
                          echo"<td><a href='administration/raiseRank/".$user['user_id']."'>povýšit uživatele</a></td>";
                          echo"<td><a href='administration/lowerRank/".$user['user_id']."'>snížit status uživatele</a></td>";
                          echo"<td><a href='administration/block/".$user['user_id']."'>blokovat uživatele</a></td>";
                          echo"<td><a href='administration/unblock/".$user['user_id']."'>odblokovat uživatele</a></td>";
                        ?>
                  </tr>
          <?php endforeach ?>
    </tbody>
  </table>
</div>