<h2>Seznam uživatelů</h2>
<?php $i = 1; ?>
<div class="table-responsive">
  <table id="userTable" class="table table-striped table-hover">
    <thead>
      <tr align="center">
        <th scope="col">Řádek</th>
        <th scope="col">ID uživatele</th>
        <th scope="col">Uživatelské jméno</th>
        <th scope="col">Status</th>
        <th scope="col">Zablokovaný</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($users as $user) : ?>
          <tr align="center"
          <?php if($user['blocked'] == true) : ?>
            class="table-danger"
          <?php elseif($user['status'] == 'administrator') : ?>
            class="table-success"
          <?php endif; ?>
          >
                      <th scope="row"><?php echo $i++;?> </th>
                      <td><?= $user['user_id'] ?></td>
                      <td><?= $user['username'] ?></td>
                      <td><strong><?= $user['status'] ?></strong></td>
                      <td><?= $user['blocked'] ?></td>
                        <?php echo"<td><a href='administration/delete/".$user['user_id']."'>odstranit uživatele</a></td>";
                         
                          echo"<td><a href='administration/raiseRank/".$user['user_id']."'>povýšit uživatele</a></td>";
                          echo"<td><a href='administration/lowerRank/".$user['user_id']."'>snížit status uživatele</a></td>";
                          echo"<td><a href='administration/block/".$user['user_id']."'>blokovat uživatele</a></td>";
                          echo"<td><a href='administration/unblock/".$user['user_id']."'>odblokovat uživatele</a></td>";
                        ?>
                  </tr>
          <?php endforeach ?>
    </tbody>
  </table>
</div>